### ISSUE TITLE
Slumbot API

### ISSUE THREAD

**Issue by BlueBoxSW** [ericgjackson/slumbot2017#12]
I was excited to read the recent paper from Deep Mind that details how they validated their bot against the Slumbot API.

I've been to your site a couple times in the past and liked what you've done.

I'm working on my own AI and thought it would be great to benchmark against the same tool to see where I stood.

However, I've tried several times over the past week to get it working and keep getting:  400 Badly formed request

I asked another developer to check in case I was doing something bone-headed and they verified that when they hit the end-point, they get the same error.

So I'm not sure if:

1) The Slumbot API is down, perhaps some https configuration issue, or similar?

2) There is some issue in that I'm using Java to hit the API and some weird encoding or JSON issue is creeping in?

3) Other?

I would appreciate any help you can give. I understand this project is kind of in in maintenance mode and you're not throwing a ton of time at it.

**Comment by ericgjackson** [comment]
I think maybe you need to set the Content-Type header of your POST requests to "application/json".  If that doesn't help, let me know.

**Comment by BlueBoxSW** [comment]
I will try that. Thanks.

**Comment by BlueBoxSW** [comment]
Turns out I was already doing that but was running into a formatting issue related to the language I was using.

Eventually got it working in cURL:
```
curl https://slumbot.com/api/new_hand/ --header "Content-Type: application/json" -X POST -d "{}"
```
And then translated to ColdFusion:
```
<cfhttp method="POST" charset="utf-8" url="https://slumbot.com/api/new_hand/" result="sb">
	<cfhttpparam type="HEADER" name="Content-Type" value="application/json">
	<cfhttpparam type="BODY" value="{}">
</cfhttp>
		
<cfset slumbot = DeserializeJSON(sb.Filecontent) >
```
