### ISSUE TITLE
Unexpected River Reveal in API

### ISSUE THREAD

**Issue by BlueBoxSW** [ericgjackson/slumbot2017#13]
Normally Slumbot only returns cards revealed while playing via API, although I'm curious to see unexposed cards but understand why you would limit this.

Anyway, I found that if:

- Player is the dealer
- On the turn, SB checks
- Player raises
- SB re-raises
- Player folds
- Returned data from API call will include river card, which was never exposed during play

Not a big deal but thought you would want to know.

**Comment by ericgjackson** [comment]
Thanks for the bug report.  I'm having trouble finding an example of this in the logs.  If you see it again, feel free to share the details with me.  Just knowing what the board cards were would probably be enough for me to find the hand in the logs.

**Comment by BlueBoxSW** [comment]
OK, I saw it twice but didn’t collect that info. If I see it again I will let you know.

Jay

**Comment by BlueBoxSW** [comment]
I never saw this again so it was likely me reading the data incorrectly from the feed.
-------------------------------------------------------------------------------------
On a side note, let me tell you how much I appreciate you putting this out there as an open resource. It has really helped me focus and refine my engine. Should you find yourself in Philadelphia for any reason, I would love the opportunity to buy you a beer, coffee, or pizza. --Poacher2023

**Comment by ericgjackson** [comment]
Thanks for letting me know that you found the API useful.  I'll take you up on that beer some time.
